# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-22 17:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(default='0', max_length=2)),
                ('votes', models.IntegerField(default=0)),
                ('image', models.ImageField(default=None, max_length=200, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='IndirizzoIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IndirizzoIP_text', models.CharField(max_length=200)),
                ('date', models.DateTimeField(verbose_name='date')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('question_image1', models.ImageField(default=None, max_length=200, upload_to='')),
                ('question_image2', models.ImageField(default=None, max_length=200, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question'),
        ),
    ]
