# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='image',
            field=models.ImageField(default='http://www.mobililoro.it/wp-content/uploads/2015/05/1-kg-carta-paglia-ecochic-gr-85-fogli-cm-70x100-tinta-unita.jpg', upload_to=''),
        ),
    ]
