# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-11 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_choice_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='choice',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
