# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_remove_question_question_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='image',
            field=models.ImageField(default=None, max_length=200, upload_to=''),
        ),
    ]
